version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '${PRISMA_PORT}:${PRISMA_PORT}'
        environment:
            PRISMA_CONFIG: |
                port: ${PRISMA_PORT}
                databases:
                  default:
                    connector: postgres
                    host: postgres
                    port: 5432
                    user: ${DB_USER}
                    password: ${DB_PASSWORD}
                    migrations: true
                    rawAccess: true
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
    dynamo:
        image: amazon/dynamodb-local
        ports:
            - "8000:8000"
volumes:
    postgres:
