version: '3'
services:
    # prisma:
    #     image: prismagraphql/prisma:1.34
    #     restart: always
    #     ports:
    #         - '${PRISMA_PORT}:${PRISMA_PORT}'
    #     environment:
    #         PRISMA_CONFIG: |
    #             port: ${PRISMA_PORT}
    #             databases:
    #               default:
    #                 connector: postgres
    #                 host: postgres
    #                 port: 5432
    #                 user: ${DB_USER}
    #                 password: ${DB_PASSWORD}
    #                 migrations: true
    #                 rawAccess: true
    graphql-engine:
        image: hasura/graphql-engine:v1.1.0
        ports:
            - '8081:8080'
        depends_on:
            - 'postgres'
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
            HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}' # set to "false" to disable console
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
            HASURA_GRAPHQL_MIGRATIONS_DIR: ${HASURA_GRAPHQL_MIGRATIONS_DIR}
            ## uncomment next line to set an admin secret
            # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
    dynamo:
        image: amazon/dynamodb-local
        ports:
            - '8000:8000'
volumes:
    postgres:
